rocr: Add WaitMultiple to core Signal
ROCm/ROCR-Runtime pull request #250
Opened 2024-10-17 18:35 UTC by atgutier

Replaces WaitAny with WaitMultiple to more closely align with the underlying driver API for waiting on multiple events.

WaitMultiple adds a single paramter, wait_on_all, to the WaitAny interface providing a single function for waiting on multiple events when we only need AND and OR semantics for the signal checking logic.

2024-11-20 17:29 UTC, atgutier commented
Any comments on this, @dayatsin-amd?

2024-12-18 19:18 UTC, dayatsin-amd approved these changes

2024-12-18 19:20 UTC, dayatsin-amd commented
> Any comments on this, @dayatsin-amd?

Looks good. Sorry for late response. Thank you for patch!

2025-01-09 23:48 UTC, atgutier commented
Can you re-review @dayatsin-amd when you get a chance? Some of the Async signal logic changed which requires additional changes to this PR that I'd like you to look at.

2025-01-21 19:57 UTC, dayatsin-amd requested changes
Some minor changes needed to avoid breaking rocprofiler function parsers.

2025-01-21 19:57 UTC, dayatsin-amd commented on runtime/hsa-runtime/core/runtime/hsa_api_trace.cpp
> +  amd_ext_api.hsa_amd_signal_wait_all_fn = AMD::hsa_amd_signal_wait_all;
This needs to go at the end (after amd_ext_api.hsa_amd_enable_logging_fn), otherwise it will break the rocprofiler ABI.

2025-01-21 19:57 UTC, dayatsin-amd commented on runtime/hsa-runtime/inc/hsa_api_trace.h
> +  decltype(hsa_amd_signal_wait_all)* hsa_amd_signal_wait_all_fn;
Needs to go at the end

2025-01-21 19:57 UTC, dayatsin-amd commented on runtime/hsa-runtime/hsacore.so.def
> +	hsa_amd_signal_wait_all;
Needs to go at the end

2025-01-21 22:18 UTC, atgutier commented on runtime/hsa-runtime/inc/hsa_api_trace.h
> +  decltype(hsa_amd_signal_wait_all)* hsa_amd_signal_wait_all_fn;
Done

2025-01-21 22:18 UTC, atgutier commented on runtime/hsa-runtime/core/runtime/hsa_api_trace.cpp
> +  amd_ext_api.hsa_amd_signal_wait_all_fn = AMD::hsa_amd_signal_wait_all;
Done

2025-01-21 22:18 UTC, atgutier commented on runtime/hsa-runtime/hsacore.so.def
> +	hsa_amd_signal_wait_all;
Done

2025-01-21 22:25 UTC, dayatsin-amd approved these changes

2025-01-24 03:53 UTC, dayatsin-amd commented
!verify full

2025-01-24 14:30 UTC, dayatsin-amd commented
!verify full

2025-01-24 17:38 UTC, atgutier commented
All comments regarding versioning should be fixed now.

2025-01-24 17:42 UTC, dayatsin-amd approved these changes

2025-01-24 17:42 UTC, dayatsin-amd commented
!verify full

2025-01-24 17:46 UTC, dayatsin-amd commented
!verify full

2025-01-27 14:22 UTC, dayatsin-amd commented
Submitted to amd-staging

2025-01-27 14:22 UTC, closed without merging