rocr/aie: AIE agent memory pools correct size and user data pool
ROCm/ROCR-Runtime pull request #265
Opened 2024-12-09 21:47 UTC by ypapadop-amd

This PR fixes the memory sizes reported for the kernarg pool and adds a pool for user data that is not the DEV HEAP or kernarg pool.

2024-12-09 22:19 UTC, atgutier approved these changes

2024-12-11 19:02 UTC, dayatsin-amd approved these changes

2024-12-12 17:00 UTC, ypapadop-amd commented
Is this a known runner error or did my PR failed?

2024-12-12 17:11 UTC, dayatsin-amd commented
Looks like an infra error

2024-12-12 17:11 UTC, dayatsin-amd commented
!verify

2025-01-24 03:44 UTC, dayatsin-amd requested changes
Can you prefix the commit subjects with "rocr/aie:"
Otherwise changes ltgm

2025-01-24 16:46 UTC, ypapadop-amd commented
> Can you prefix the commit subjects with "rocr/aie:" Otherwise changes ltgm

All done.

2025-01-24 17:03 UTC, dayatsin-amd approved these changes

2025-01-27 16:51 UTC, dayatsin-amd commented
!verify full

2025-01-28 00:33 UTC, dayatsin-amd commented
!verify

2025-01-28 15:56 UTC, dayatsin-amd commented
Merged into amd-staging

2025-01-28 15:56 UTC, closed without merging